version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps:
      - run:
          name: Install dependencies
          command: apt-get update; apt-get install -yq pkg-config libssl-dev
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test

      - run:
          name: Clone Fluent PostgreSQL
          command: git clone -b nio git@github.com:vapor/fluent-postgresql.git
          working_directory: ~/
      - run:
          name: Switch Fluent PostgreSQL to this Fluent revision
          command: swift package edit Fluent --revision $CIRCLE_SHA1
          working_directory: ~/fluent-postgresql
      - run:
          name: Run Fluent PostgreSQL unit tests
          command: swift test
          working_directory: ~/fluent-postgresql

      - run: 
          name: Compile code with optimizations
          command: swift build -c release
workflows:
  version: 2
  tests:
    jobs:
      - linux
      # - macos
